runtime: nodejs18
entrypoint: "echo 'Static site, no server needed'"

handlers:
  - url: /(.*\.(html|css|js|png|jpg|jpeg|gif|svg|ico|woff|woff2|ttf|eot|mp3))
    static_files: dist/\1
    upload: dist/.*\.(html|css|js|png|jpg|jpeg|gif|svg|ico|woff|woff2|ttf|eot|mp3)
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html