name: Deploy Backend to Google Compute Engine

on:
  push:
    branches: [main]
    paths: ["Server/**"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: { node-version: "18" }
      - run: |
          npm install
          npm run build
        working-directory: ./Server
      - run: |
          echo "${{ secrets.GCE_SSH_PRIVATE_KEY }}" > ssh_key
          chmod 600 ssh_key
      - run: |
          ssh -i ssh_key -o StrictHostKeyChecking=no ${{ secrets.GCE_SSH_USER }}@${{ secrets.GCE_SSH_HOST }} << 'EOF'
            cd ~/NewLearn-MERN-LMS || git clone ${{ github.repository }} NewLearn-MERN-LMS && cd ~/NewLearn-MERN-LMS
            git pull origin main
            cd Server
            echo "${{ secrets.SERVER_ENV }}" > .env  # Add .env file
            npm install
            npm run build
            pm2 reload lms-backend || pm2 start dist/server.js --name lms-backend
            sudo systemctl reload nginx
          EOF
      - run: rm -f ssh_key